config/routes.rb
Mine::Application.routes.draw do

root 'tasks#index'

resources :projects

resources :blog_links

resources :timelines

resources :users

resources :links

resources :careers

resources :studies

resources :fit_posts

get "/trails" =>  "tasks#trails",               as: "trails"
get "/tasks/calendar" =>  "tasks#calendar",     as: "calendar"
get "/tasks/archive" =>  "tasks#archive",       as: "archive"
get "/tasks/notes/:id" =>  "tasks#notes",       as: "notes"
get "/practice1" =>  "studies#practice1",       as: "practice1"
get "/practice2" =>  "studies#practice2",       as: "practice2"
get "/practice3" =>  "studies#practice3",       as: "practice3"
get "/dv_class_blogs" => "blog_links#dv_blogs", as: "dv_blogs"
get "/challenge"  => "fit_posts#challenge",     as: "challenge"

resources :tasks
end

app/models/blog_link.rb
class BlogLink < ActiveRecord::Base
end

app/controllers/blog_links_controller.rb
class BlogLinksController < ApplicationController
  before_action :set_blog_link, only: [:show, :edit, :update, :destroy]

  # GET /blog_links
  # GET /blog_links.json
  def index
    @blog_links = BlogLink.all
  end

  # GET /blog_links/1
  # GET /blog_links/1.json
  def show
  end
  
  def dv_blogs
    @blog_links = BlogLink.where(category: "DV Class Blogs")
    render :dv_class and return
  end


  # GET /blog_links/new
  def new
    @blog_link = BlogLink.new
  end

  # GET /blog_links/1/edit
  def edit
  end

  # POST /blog_links
  # POST /blog_links.json
  def create
    @blog_link = BlogLink.new(blog_link_params)

    respond_to do |format|
      if @blog_link.save
        format.html { redirect_to @blog_link, notice: 'Blog link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_links/1
  # PATCH/PUT /blog_links/1.json
  def update
    respond_to do |format|
      if @blog_link.update(blog_link_params)
        format.html { redirect_to @blog_link, notice: 'Blog link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_links/1
  # DELETE /blog_links/1.json
  def destroy
    @blog_link.destroy
    respond_to do |format|
      format.html { redirect_to blog_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_link
      @blog_link = BlogLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_link_params
      params.require(:blog_link).permit(:link, :description, :category)
    end
end

app/helpers/blog_links_helper.rb
module BlogLinksHelper
end

app/views/blog_links/_form.html.erb
<%= form_for(@blog_link) do |f| %>
  <% if @blog_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_link.errors.count, "error") %> prohibited this blog_link from being saved:</h2>

      <ul>
      <% @blog_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_links/dv_class.html.erb
<h1>Listing blog_links</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Description</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_links.each do |blog_link| %>
      <tr>
        <td class="pad"><a href="<%= blog_link.link %>"><%= blog_link.link %></a></td>
        <td class="pad"><%= blog_link.description %></td>
        <td class="pad"><%= blog_link.category %></td>
        <td class="pad"><%= link_to 'Show', blog_link %></td>
        <td class="pad"><%= link_to 'Edit', edit_blog_link_path(blog_link) %></td>
        <td class="pad"><%= link_to 'Destroy', blog_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', tasks_path %>

app/views/blog_links/edit.html.erb
<h1>Editing blog_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_link %> |
<%= link_to 'Back', blog_links_path %>

app/views/blog_links/index.html.erb
<h1>Listing blog_links</h1> <%= link_to "DV class", dv_blogs_path %>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Description</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_links.each do |blog_link| %>
      <tr>
        <td class="pad"><a href="<%= blog_link.link %>"><%= blog_link.link %></a></td>
        <td class="pad"><%= blog_link.description %></td>
        <td class="pad"><%= blog_link.category %></td>
        <td class="pad"><%= link_to 'Show', blog_link %></td>
        <td class="pad"><%= link_to 'Edit', edit_blog_link_path(blog_link) %></td>
        <td class="pad"><%= link_to 'Destroy', blog_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog link', new_blog_link_path %>

app/views/blog_links/new.html.erb
<h1>New blog_link</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_links_path %>

app/views/blog_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @blog_link.link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog_link.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blog_link.category %>
</p>

<%= link_to 'Edit', edit_blog_link_path(@blog_link) %> |
<%= link_to 'Back', blog_links_path %>