config/routes.rb
Mine::Application.routes.draw do

root 'tasks#index'

resources :projects

resources :blog_links

resources :timelines

resources :users

resources :links

resources :careers

resources :studies

resources :fit_posts

get "/trails" =>  "tasks#trails",               as: "trails"
get "/tasks/calendar" =>  "tasks#calendar",     as: "calendar"
get "/tasks/archive" =>  "tasks#archive",       as: "archive"
get "/tasks/notes/:id" =>  "tasks#notes",       as: "notes"
get "/practice1" =>  "studies#practice1",       as: "practice1"
get "/practice2" =>  "studies#practice2",       as: "practice2"
get "/practice3" =>  "studies#practice3",       as: "practice3"
get "/dv_class_blogs" => "blog_links#dv_blogs", as: "dv_blogs"
get "/challenge"  => "fit_posts#challenge",     as: "challenge"

resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
#     if params[:search].present?
#       LocationFetcher.fetch(params[:search])
#       first_word = params[:search].split(/[\s,]+/).first
#       @locations = Location.search(first_word).order(updated_at: :desc)
#       if @locations.empty?
#         flash[:notice] = "\'#{params[:search].capitalize}\' queued for import.
#           Please refresh the page if the new location doesn't appear below right away."
#       end
#       redirect_to locations_path
#     else
#       @locations = Location.order(updated_at: :desc).paginate(:page => params[:page])
#     end
    tasks = Task.where(completed: false)
    if params[:format] == "priority"
      @tasks = tasks.order(:priority).page(params[:page]).per_page(5)
    else
      @tasks = tasks.order(:deadline).page(params[:page]).per_page(5)
    end
  end
  
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end
  
  def calendar
  end
  
  def notes
    @task = Task.find(params[:id])
  end
  
  def archive
    @tasks = Task.all.page(params[:page]).per_page(10)
  end
 
  def trails
    render :trails, layout: false and return
  end
 

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        @task.just_date = @task.deadline.to_date
        @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        @task.just_date = @task.deadline.to_date
        @task.save
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:done_for_today, :name, :deadline, :completed, :date_completed, :priority, :notes, :links, :category, :sub_category, :contact, :location, :comm_info, :last_worked_on)
    end
  
end

app/helpers/tasks_helper.rb
module TasksHelper

  def category_select
    [
    ["Programming"],
    ["Networking"],
    ["Social"],
    ["Finance"],
    ["Household"],
    ["Personal"]
    ]
  end

  def sub_category_select
    [
    ["New Career Process Prep"],
    ["Friend / Family"],
    ["Reading"],
    ["Coding"],
    ["MeetUp"],
    ["Bootcamp"],
    ["Health"],
    ["Budget / Bill"]
    ]
  end
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :rows => 2, :cols => 50 %>
  </div>
  <div class="field">
    <%= f.label :done_for_today %><br>
    <%= f.check_box :done_for_today %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :date_completed %><br>
    <%= f.datetime_select:date_completed %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :links %><br>
    <%= f.text_field :links %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(category_select, @task.category) %>
  </div>
  <div class="field">
    <%= f.label :sub_category %><br>
    <%= f.select :sub_category, options_for_select(sub_category_select, @task.sub_category) %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :comm_info %><br>
    <%= f.text_field :comm_info %>
  </div>
  <div class="field">
    <%= f.label :last_worked_on %><br>
    <%= f.datetime_select :last_worked_on %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-info' %> 
  </div>
<% end %>

app/views/tasks/archive.html.erb
<h1 style="color: black">Archived<i>tasks</i></h1>
<div class="container row">
<table class="table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last worked on</th>
      <th>Deadline</th>
      <th>Date completed</th>
      <th>Notes</th>
      <th>Links</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.order(:deadline).each do |task| %>
      <% if task.completed == true %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.last_worked_on.strftime("%b/%-d") %></td>
        <td><p style="color: green"><%= task.deadline.strftime("%m/%d/%y @ %H:%M") %></p></td>
        <td><b><%= task.date_completed.strftime("%b %-d, %Y") %></b></td>
        <td><p style="color: black"><%= task.notes.chars[0..20].join %></p>
        <% if task.notes.length > 20 %>
          <u><a href="/tasks/notes/<%= task.id %>" style="color: blue">more...</a></u></td>
        <% end %>
        <td><%= task.links.chars[0..10].join %></td>
        <td><p style="color: #550808"><%= task.category %></p></td>
        <td><%= link_to 'Show', task, {:style=>'color:white;', :class => "btn btn-success"} %></td>
        <td><%= link_to 'Edit', edit_task_path(task), {:style=>'color:white;', :class => "btn btn-info"} %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary', :style => 'color: white;'%></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-dirt"} %>

Notes: Archive tasks that might for reference of accomplishments, possible resume / interview examples  or things to make note of before deletion.

app/views/tasks/calendar.html.erb
<p id="notice"><%= notice %></p>
<div class="pull-left">
  <%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-dirt"} %>
</div>
<center>
  <h2 style="color: #1E5A53">Calendar</h2>
</center><br></br>
<table class="table-striped" width = "1400">
  <thead>
    <tr>
      <th><%= DateTime.now.strftime("%b %a %d") %></th>
      <% x = 0 %>
      <% while x < 6 %>
      <% x = x + 1 %>
      <th><%= (Date.today + x).strftime("%a %d")%></th>
      <% end %>
    </tr>
    <tr>
      <% x = -1 %>
      <% while x < 8 %>
        <% x = x + 1 %>
          <td width="200" height="100">
            <%Task.where(just_date: Date.today.to_date + x).each do |t| %>
               <%= t.name %>
               <%= t.deadline.strftime("%I:%M") %><br>
             <%end%>
           </td>
      <% end %> 
    </tr>
    <tr>
      <% x = 6 %>
      <% while x > 5 && x < 13 %>
      <% x = x + 1 %>
      <th><%= (Date.today + x).strftime("%a %d")%></th>
      <% end %>
    </tr>
    <tr>
      <% x = 6 %>
      <% while x > 5 && x < 13 %>
        <% x = x + 1 %>
          <td width="200" height="100">
            <%Task.where(just_date: Date.today.to_date + x).each do |t| %>
               <%= t.name %>
               <%= t.deadline.strftime("%I:%M") %><br>
             <%end%>
           </td>
      <% end %> 
    </tr>
    <tr>
      <% x = 13 %>
      <% while x > 12 && x < 20 %>
      <% x = x + 1 %>
      <th><%= (Date.today + x).strftime("%a %d")%></th>
      <% end %>
    </tr>
    <tr>
      <% x = 13 %>
      <% while x > 12 && x < 20 %>
        <% x = x + 1 %>
          <td width="200" height="100">
            <%Task.where(just_date: Date.today.to_date + x).each do |t| %>
               <%= t.name %>
               <%= t.deadline.strftime("%I:%M") %><br>
             <%end%>
           </td>
      <% end %> 
    </tr>
    <tr>
      <% x = 20 %>
      <% while x > 19 && x < 27 %>
      <% x = x + 1 %>
      <th><%= (Date.today + x).strftime("%a %d")%></th>
      <% end %>
    </tr>
    <tr>
      <% x = 20 %>
      <% while x > 19 && x < 27 %>
        <% x = x + 1 %>
          <td width="200" height="100">
            <%Task.where(just_date: Date.today.to_date + x).each do |t| %>
               <%= t.name %>
               <%= t.deadline.strftime("%I:%M") %><br>
             <%end%>
           </td>
      <% end %> 
    </tr>
  </thead>
 

app/views/tasks/edit.html.erb
<div class="row">
<div class="col-md-3">
  <h1>Editing task</h1>
</div>
<div class="col-md-3">
  <%= link_to 'Show', @task, {:style=>'color:white;', :class => "btn btn-success"} %> |
  <%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-dirt"} %>
</div>
</div>


<%= render 'form' %>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'tasks' %>
<ul class='nav nav-pills task_nav round-this'>
  <li><%= link_to 'New Task', new_task_path, {:style=>'color:#7D7665;', :class => 'btn btn-default'} %></li>
  <li><%= link_to 'Projects', projects_path, {:style=>'color:white;', :class => 'btn btn-dirt'} %></li>
  <li><%= link_to 'Career', careers_path(:priority), {:style=>'color:white;', :class => 'btn btn-dirt'} %></li>
  <li><%= link_to 'Study', studies_path, {:style=>'color:white;', :class => 'btn btn-dirt'} %></li>
  <li><%= link_to 'Fit Post', fit_posts_path, {:style=>'color:white;', :class => 'btn btn-dirt'} %></li>
  <li><%= link_to 'Priority', tasks_path(:priority), {:style=>'color:white;', :class => 'btn btn-info'} %></li>
  <li><%= link_to 'Archive', archive_path, {:style=>'color:white;', :class => 'btn btn-info'} %></li>
  <li><a class='btn btn-info' style='color: white;' href='/tasks/calendar'>Calendar</a></li>
  <li><a class='btn btn-default' style='color: #3579A5;' href='http://www.weather.com/weather/hourbyhour/graph/80227'>Weather</a></li>
  <li><a class='btn btn-default' style='color: #3579A5;' href='http://finance.yahoo.com/q;_ylt=AsCON6EETHyuQCXV57HQ93Inv7gF?uhb=uh3_finance_vert_gs_ctrl2&fr=uh3_finance_vert_gs_ctrl2_e&type=2button&s=c'>Quote</a></li>
</ul>
<h1 style='color: #7D7665; text-shadow: 1px 4px 1px white;'><%= Date.today.strftime( '%A' ) %><i>tasks</i></h1>
<table class='table-striped'>
  <thead>
    <tr>
      <th></th>
      <th class='pad center-this'>
          Name</th>
      <th>Deadline</th>
      <th>Priority</th>
      <th>Notes</th>
      <th>Link</th>
      <th>Category</th>
      <th>Contact</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody style='text-align: center;'>
    <% @tasks.each do |task| %>
      <tr>
      <% if task.completed == false %>
        <td  width='50'><div class='field'>
          <% if DateTime.now.day == task.updated_at.day %>
            <%= check_box_tag :done_for_today, '', task.done_for_today %>
          <% else %>
            <%= check_box_tag :done_for_today, '', false %>
          <% end %>
            </div>
        </td>
        <td width='150'>
          <% if Time.now >= task.deadline - (60*60*24)%>
            <p style='color: #7D7665'><b><%= task.name %></b></p>
          <% elsif Time.now <= task.deadline - (60*60*24*15)%>
            <p style='color: silver'><%= task.name %></p>
          <% else %>
            <%= task.name %>
          <% end %>
        </td>
        <td width='120'><b><%= task.deadline.strftime('%a, %d, %H:%M') %></b></td>
        <% if task.priority == 1 %>
          <td class='center-this' width='50'><p style='color: #7D7665'><b><%= task.priority %></b></p></td>
        <% else %>
          <td class='center-this' width='50'><%= task.priority %></td>
        <% end %>
        <td width='170'><p><%= task.notes.chars[0..20].join %></p>
        <% if task.notes.length > 20 %>
          <u><a href='/tasks/notes/<%= task.id %>' style='color: #7D7665'>more...</a></u></td>
        <% end %>
        <td width='110'> <a style="color: #927017;" href="http://<%= task.links %>"><%= task.links.chars[0..12].join %><a></td>
        <td width='110'><p><%= task.category.chars[0..12].join %></p></td>
        <td width='110'><%= task.contact %></td>
        <td><%= link_to 'Show', task, {:style=>'color:white;', :class => 'btn btn-forest'} %></td>
        <td><%= link_to 'Edit', edit_task_path(task), {:style=>'color:white;', :class => 'btn btn-dirt'} %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-info', :style => 'color: white;'%></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<div><br/>
<% Study.all.each do |s| %>
  <% if s.priority == 1 && DateTime.now >= s.deadline %>
    <b style="color: #7D7665"><%= "FYI - Study Task '#{s.name}' is due today" %></b>
  <% end %>
<% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-md-3">
    <h1>New task</h1>
  </div>
  <div class="col-md-3">
  <%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-dirt"} %>
</div>
</div>
<%= render 'form' %>

app/views/tasks/notes.html.erb
<p id="notice"><%= notice %></p>


<h3 style="color: rgba(6, 72, 133, 0.85)">
  <strong>Notes:</strong><br></br>
  <p><%= @task.notes %></p>
</h3>
<br></br>



<%= link_to 'Edit', edit_task_path(@task), {:style=>'color:white;', :class => 'btn btn-info'} %> |
<%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-primary"} %>
test
<script>console.log("testing javascript");</script>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Date completed:</strong>
  <%= @task.date_completed %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @task.notes %>
</p>

<p>
  <strong>Links:</strong>
  <%= @task.links %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category %>
</p>

<p>
  <strong>Sub Category:</strong>
  <%= @task.sub_category %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @task.contact %>
</p>

<p>
  <strong>Location:</strong>
  <%= @task.location %>
</p>

<p>
  <strong>Comm info:</strong>
  <%= @task.comm_info %>
</p>

<p>
  <strong>Last worked on:</strong>
  <%= @task.last_worked_on %>
</p>

<%= link_to 'Edit', edit_task_path(@task), {:style=>'color:white;', :class => "btn btn-info"} %> |
<%= link_to 'Back', tasks_path, {:style=>'color:white;', :class => "btn btn-dirt"} %>