config/routes.rb
Mine::Application.routes.draw do

root 'tasks#index'

resources :projects

resources :blog_links

resources :timelines

resources :users

resources :links

resources :careers

resources :studies

resources :fit_posts

get "/trails" =>  "tasks#trails",               as: "trails"
get "/tasks/calendar" =>  "tasks#calendar",     as: "calendar"
get "/tasks/archive" =>  "tasks#archive",       as: "archive"
get "/tasks/notes/:id" =>  "tasks#notes",       as: "notes"
get "/practice1" =>  "studies#practice1",       as: "practice1"
get "/practice2" =>  "studies#practice2",       as: "practice2"
get "/practice3" =>  "studies#practice3",       as: "practice3"
get "/dv_class_blogs" => "blog_links#dv_blogs", as: "dv_blogs"
get "/challenge"  => "fit_posts#challenge",     as: "challenge"

resources :tasks
end

app/models/fit_post.rb
class FitPost < ActiveRecord::Base
end

app/controllers/fit_posts_controller.rb
class FitPostsController < ApplicationController
  before_action :set_fit_post, only: [:show, :edit, :update, :destroy]

  # GET /fit_posts
  # GET /fit_posts.json
  def index
    @fit_posts = FitPost.order(:date).reverse
  end
  
  def challenge
    if FitPost.last.check_weight != nil
      @check_weight = FitPost.last.check_weight
    else
      @check_weight = 145
    end
  end
  # GET /fit_posts/1
  # GET /fit_posts/1.json
  def show
  end

  # GET /fit_posts/new
  def new
    @fit_post = FitPost.new
  end

  # GET /fit_posts/1/edit
  def edit
  end

  # POST /fit_posts
  # POST /fit_posts.json
  def create
    @fit_post = FitPost.new(fit_post_params)
    @fit_post.check_weight = 170.5
    respond_to do |format|
      if @fit_post.save
        format.html { redirect_to @fit_post, notice: 'Fit post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fit_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @fit_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fit_posts/1
  # PATCH/PUT /fit_posts/1.json
  def update
    respond_to do |format|
      if @fit_post.update(fit_post_params)
        format.html { redirect_to @fit_post, notice: 'Fit post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fit_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fit_posts/1
  # DELETE /fit_posts/1.json
  def destroy
    @fit_post.destroy
    respond_to do |format|
      format.html { redirect_to fit_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fit_post
      @fit_post = FitPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fit_post_params
      params.require(:fit_post).permit(:date, :weight, :focus, :breakfast, :brk_cals, :lunch, :lunch_cals, :dinner, :dinner_cals, :snacks, :snack_cals, :cal_track_complete, :water_extract_64oz, :exercise, :accomplishment, :model_day, :energy, :notes)
    end
end

app/helpers/fit_posts_helper.rb
module FitPostsHelper
end

app/views/fit_posts/_form.html.erb
<%= form_for(@fit_post) do |f| %>
  <% if @fit_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fit_post.errors.count, "error") %> prohibited this fit_post from being saved:</h2>

      <ul>
      <% @fit_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :focus %><br>
    <%= f.text_area :focus %>
  </div>
  <div class="field">
    <%= f.label :breakfast %><br>
    <%= f.text_field :breakfast %>
  </div>
  <div class="field">
    <%= f.label :brk_cals %><br>
    <%= f.text_field :brk_cals %>
  </div>
  <div class="field">
    <%= f.label :lunch %><br>
    <%= f.text_field :lunch %>
  </div>
  <div class="field">
    <%= f.label :lunch_cals %><br>
    <%= f.number_field :lunch_cals %>
  </div>
  <div class="field">
    <%= f.label :dinner %><br>
    <%= f.text_field :dinner %>
  </div>
  <div class="field">
    <%= f.label :dinner_cals %><br>
    <%= f.number_field :dinner_cals %>
  </div>
  <div class="field">
    <%= f.label :snacks %><br>
    <%= f.text_field :snacks %>
  </div>
  <div class="field">
    <%= f.label :snack_cals %><br>
    <%= f.number_field :snack_cals %>
  </div>
  <div class="field">
    <%= f.label :cal_track_complete %><br>
    <%= f.check_box :cal_track_complete %>
  </div>
  <div class="field">
    <%= f.label :water_extract_64oz %><br>
    <%= f.check_box :water_extract_64oz %>
  </div>
  <div class="field">
    <%= f.label :exercise %><br>
    <%= f.text_field :exercise %>
  </div>
  <div class="field">
    <%= f.label :accomplishment %><br>
    <%= f.text_area :accomplishment %>
  </div>
  <div class="field">
    <%= f.label :model_day %><br>
    <%= f.check_box :model_day %>
  </div>
  <div class="field">
    <%= f.label :energy %><br>
    <%= f.check_box :energy %>
  </div>
  <div class="field">
    <%= f.label :check_weight %><br>
    <%= f.number_field :check_weight %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :rows => 20, :cols => 70 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fit_posts/challenge.html.erb
<%= stylesheet_link_tag 'challenge' %>
<header class='header' >
  <p class='pad center-this' style='font-family: moonspace; font-size: 40px; color: #731817; text-shadow: 2px 2px 2px white;'>Challenge</p>
  <nav>
  <%= link_to 'Home', tasks_path, {:style=>'color:white;', :class => 'btn btn-orange'} %>
  </nav>
</header></br>

<div class='jumbotron center-this'>
  <h3>MTB - Make it to the top of Mt Falcon without clipping out!</h3>
</div>

<!--
<%#= @check_weight %><br>
Last Weigh In: <%#= FitPost.last.weight %><br>
Next Weigh In: <%#= FitPost.last.weight %> or lower.<br>
Exception:<%#= FitPost.last.weight %><br>

Need to work on number field for check weight. Hard coded in controller at the moment

app/views/fit_posts/edit.html.erb
<h1>Editing fit_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @fit_post %> |
<%= link_to 'Back', fit_posts_path %>

app/views/fit_posts/index.html.erb
<%= stylesheet_link_tag "fit_posts" %>
<header class="header" >
<center><p class="pad" style="font-family: moonspace; font-size: 40px; color: #CDB47E; text-shadow: 2px 2px 2px white;">Daily Health Journal</p></center>
<nav>
<%= link_to 'Home', tasks_path, {:style=>'color:white;', :class => "btn btn-orange"} %>
<%= link_to 'New Fit post', new_fit_post_path, {:style=>'color: #002041;', :class => "btn btn-white"} %>
<%= link_to 'Challenge', challenge_path, {:style=>'color: #002041;', :class => "btn btn-white"} %>
</nav>
</header>

<table class="table-striped">
  <thead class>
    <tr>
      <th class="pad"><center>Date</center></th>
      <th class="pad"><center>Total Calories</center></th>
      <th class="pad"><center>Weight</center></th>
      <th class="pad"><center>Focus</center></th>
      <th class="pad"><center>Breakfast</center></th>
      <th class="pad"><center>Lunch</center></th>
      <th class="pad"><center>Dinner</center></th>
      <th class="pad"><center>Snacks</center></th>
      <th class="pad"><center>Calorie tracking complete</center></th>
      <th class="pad"><center>Exercise</center></th>
      <th class="pad"><center>Model day</center></th>
    </tr>
  </thead>

  <tbody>
    <% @fit_posts.each do |fit_post| %>
      <tr>
        <td><center><%= fit_post.date.strftime("%d") %></center></td>
        <% if fit_post.brk_cals != nil && fit_post.lunch_cals != nil && fit_post.dinner_cals != nil && fit_post.snack_cals != nil%>
          <td><center><%= fit_post.brk_cals + fit_post.lunch_cals + fit_post.dinner_cals + fit_post.snack_cals%><center></td>
        <% else %>
          <td><center>not entered</center></td>
        <% end %>
        <td><center><%= fit_post.weight %></center></td>
        <td><center><%= fit_post.focus %></center></td>
        <td><center><%= fit_post.breakfast %></center></td>
        <td><center><%= fit_post.lunch %></center></td>
        <td><center><%= fit_post.dinner %></center></td>
        <td><center><%= fit_post.snacks %></center></td>
        <% if fit_post.cal_track_complete == true %>
          <td><center>Yes</center></td>
        <% else %>
          <td></td>
        <% end %>
        <td><center><%= fit_post.exercise %></center></td>
        <% if fit_post.model_day == true %>
          <td><center>Yes</center></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', fit_post, {:style=>'color:white;', :class => 'btn btn-orange'} %></td>
        <td><%= link_to 'Edit', edit_fit_post_path(fit_post), {:style=>'color:white;', :class => 'btn btn-blue'} %></td>
        <td><%= link_to 'Destroy', fit_post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-white', :style => 'color: #002041;' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fit_posts/new.html.erb
<h1>New fit_post</h1>

<%= render 'form' %>

<%= link_to 'Back', fit_posts_path %>

app/views/fit_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @fit_post.date %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @fit_post.weight %>
</p>

<p>
  <strong>Focus:</strong>
  <%= @fit_post.focus %>
</p>

<p>
  <strong>Breakfast:</strong>
  <%= @fit_post.breakfast %>
</p>

<p>
  <strong>Brk cals:</strong>
  <%= @fit_post.brk_cals %>
</p>

<p>
  <strong>Lunch:</strong>
  <%= @fit_post.lunch %>
</p>

<p>
  <strong>Lunch cals:</strong>
  <%= @fit_post.lunch_cals %>
</p>

<p>
  <strong>Dinner:</strong>
  <%= @fit_post.dinner %>
</p>

<p>
  <strong>Dinner cals:</strong>
  <%= @fit_post.dinner_cals %>
</p>

<p>
  <strong>Snacks:</strong>
  <%= @fit_post.snacks %>
</p>

<p>
  <strong>Snack Cals:</strong>
  <%= @fit_post.snack_cals %>
</p>

<p>
  <strong>Water extract 64oz:</strong>
  <%= @fit_post.water_extract_64oz %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @fit_post.exercise %>
</p>

<p>
  <strong>Accomplishment:</strong>
  <%= @fit_post.accomplishment %>
</p>

<p>
  <strong>Model day:</strong>
  <%= @fit_post.model_day %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @fit_post.energy %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @fit_post.notes %>
</p>

<%= link_to 'Edit', edit_fit_post_path(@fit_post) %> |
<%= link_to 'Back', fit_posts_path %>