config/routes.rb
Mine::Application.routes.draw do

root 'tasks#index'

resources :projects

resources :blog_links

resources :timelines

resources :users

resources :links

resources :careers

resources :studies

resources :fit_posts

get "/trails" =>  "tasks#trails",               as: "trails"
get "/tasks/calendar" =>  "tasks#calendar",     as: "calendar"
get "/tasks/archive" =>  "tasks#archive",       as: "archive"
get "/tasks/notes/:id" =>  "tasks#notes",       as: "notes"
get "/practice1" =>  "studies#practice1",       as: "practice1"
get "/practice2" =>  "studies#practice2",       as: "practice2"
get "/practice3" =>  "studies#practice3",       as: "practice3"
get "/dv_class_blogs" => "blog_links#dv_blogs", as: "dv_blogs"
get "/challenge"  => "fit_posts#challenge",     as: "challenge"

resources :tasks
end

app/models/study.rb
class Study < ActiveRecord::Base
  serialize :material 
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.order(:priority)
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end
    
  def practice1
    render :practice1, layout: false and return
  end
  
  def practice2
#     require 'open-uri'
#     require 'json'
#       url = JSON.parse("http://ats-rails-project.herokuapp.com.json").to_s
#       open(url) do |http|
#       @response = http.read
#       @response = @response[0]
#       end
    render :practice2, layout: false and return
  end
  
   def practice3
    render :practice3, layout: false and return
  end
  
  
  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)
    respond_to do |format|
#         @study.material = {:name => @study.name, :links => @study.links, :not_a_column => params[:test]}
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render action: 'show', status: :created, location: @study }
      else
        format.html { render action: 'new' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:name, :next_up, :done_for_today, :deadline, :priority, :category, :links, :material, :completed, :notes)
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= stylesheet_link_tag "studies" %>
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="pull-left">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :next_up %><br>
    <%= f.text_area :next_up, :rows => 20, :cols => 70 %>
  </div>
  </div>
  <div class = "pull-right">
  <div class="field">
    <%= f.label :done_for_today %><br>
    <%= f.check_box :done_for_today %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :links %><br>
    <%= f.text_field :links %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  </div>
  <div class="actions pad">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>
<%= stylesheet_link_tag "studies" %>
<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<%= stylesheet_link_tag "studies" %>
<ul class="nav nav-pills pull-center studies_nav">
  <li><%= link_to 'New Study Task', new_study_path, {:style=>'color:#FDFFD3;', :class => "btn btn-white"} %></li>
  <li><%= link_to 'Home', tasks_path, {:style=>'color:#FDFFD3;', :class => "btn btn-blue"} %></li>
  <li><%= link_to 'Links', links_path, {:style=>'color:#FDFFD3;', :class => 'btn btn-blue'} %></li>
  <li><%= link_to 'Blogs', blog_links_path, {:style=>'color:#FDFFD3;', :class => 'btn btn-blue'} %></li>
  <li><%= link_to 'Timeline', timelines_path, {:style=>'color:#FDFFD3;', :class => 'btn btn-blue'} %></li>
  <% x = 1 %>
  <% while x > 0 && x < 4 %>
    <li><a class="btn btn-yellow" style="color: #301100; "href="/practice<%= x %>">Practice<%= x %></a></li>
    <% x += 1 %>
  <% end %>
</ul>
<!--<div class="title_bar">-->
  <!--<b>Studying</b><br>-->
<!--</div>-->
<table class="table-striped pad">
  <thead>
    <tr>
      <th class="pad">Name</th>
      <th class="pad">Next up</th>
      <th class="pad">Day</th>
      <th class="pad">Priority</th>
      <th class="pad">Category</th>
      <th class="pad">Links</th>
      <th class="pad">Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td width="150">
          <% if Time.now >= study.deadline - (60*60*24)%>
            <p style="color: #301100"><b><%= study.name %></b></p>
          <% elsif Time.now <= study.deadline - (60*60*24*15)%>
            <p style="color: #EE8446"><%= study.name %></p>
          <% else %>
            <%= study.name %>
          <% end %>
        </td>
        <td class="pad"><%= study.next_up.chars[0..20].join %></td>
        <td class="pad"><center><%= study.deadline.strftime("%d") %></center></td>
        <td class="pad"><center><%= study.priority %></center></td>
        <td class="pad"><%= study.category %></td>
        <td class="pad"><a href="http://<%= study.links %>"><%= study.links.chars[0..10].join %></a></td>
        <td class="pad"><%= study.notes.chars[0..10].join %></td>
        <td class="pad"><%= link_to 'Show', study, {:style=>'color:#FDFFD3;', :class => 'btn btn-blue'} %></td>
        <td class="pad"><%= link_to 'Edit', edit_study_path(study), {:style=>'color:#301100;', :class => 'btn btn-yellow'} %></td>
        <td class="pad"><%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-white', :style =>'color:#FDFFD3;' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/studies/new.html.erb
<h1>New study</h1>
<%= stylesheet_link_tag "studies" %>
<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/practice1.html.erb
<%= stylesheet_link_tag "main" %>
<!doctype html>
<html lang=“en”>
<head>
<meta charset=“utf-8”>
<title>Explore California Trail Guide</title>
<link rel=“stylesheet” href=“assets/stylesheet/main.css” media=“screen, projection”>
<script src=“_scripts/jquery-1.5.1.min.js”></script>
</head>
<body>
  <header id=“mainHeader”>
  <hgroup>
  <!-- <hgroup> ranks title to show, <span> hides --!>
	<h1><span>Explore California</span>Trail Guide</h1> 
	<h2>your complete biking trail source</h2>
	</hgroup>
<nav>
  <h2>Main page navigation</h2> <!-- this will be hidden with css  --!>     
  <ul>
    <li><a href="http://www.explorecalifornia.org" title="Visit Explore California">explore california</a></li>
    <li><a href="trails.htm" title="Trail Reviews" class="current">trail reviews</a></li>
    <li><a href="news.htm" title="Trail News">trail news</a></li>
    <li><a href="resources.htm" title="Trail Resources">resources</a></li>
    <li><a href="http://www.explorecalifornia.org/tours.htm" title="Biking Tours">tours</a></li>
   </ul>
</nav>
</header>
<section id=“trailReviews”>
  <header>
    <h2>Trail Reviews</h2>
    <h3>All Trails</h3>
    <dl>
     <dt>Butte</dt>
       <dd><a href="#" title="our trails">Chico Airport Trail</a></dd>
       <dd><a href="#" title="our trails">Chico West Loop</a></dd>
     <dt>Contra Costa
       <dd><a href="#" title="our trails">Black Diamond Railway</a></dd>
       <dd><a href="#" title="our trails">Contra Costa Canal</a></dd>
       <dd><a href="#" title="our trails">Delta De Anza Fire Loop</a></dd>
     <dt>El Dorado</dt>
       <dd><a href="#" title="our trails">Mission Flat</a></dd>
       <dd><a href="#" title="our trails">South Lake Tahoe</a></dd>
     <dt>Imperial</dt>
       <dd><a href="#" title="our trails">Imperial Valley Ridge Loop</a></dd>
     <dt>Marin</dt>
       <dd><a href="#" title="our trails">Larkspur Path</a></dd>
       <dd><a href="#" title="our trails">Old Rail Grand Loop</a></dd>
       <dd><a href="#" title="our trails">Sir Francis Drake Trail</a></dd>
     <dt>Mono</dt>
       <dd><a href="#" title="our trails">Chateau Road Connector</a></dd>
       <dd><a href="#" title="our trails">Chico West Loop</a></dd>
       <dd><a href="#" title="our trails">Lake Mary Road</a></dd>
       <dd><a href="#" title="our trails">Mammoth Creek West</a></dd>
       <dd><a href="#" title="our trails">Shady Rest Loop</a></dd>
     <dt>Ojai</dt>
        <dd><a href="trails.htm" title="our trails">Northridge Loop</a></dd>
        <dd><a href="#" title="our trails">Ojai Inn Loop</a></dd>
     <dt>Orange County</dt>
       <dd><a href="#" title="our trails">Castaways Trail</a></dd>
       <dd><a href="#" title="our trails">Dana Headlands Over Spur</a></dd>
       <dd><a href="#" title="our trails">Pacific Electric Trail</a></dd>
     <dt>Sacramento</dt>
       <dd><a href="#" title="our trails">American River</a></dd>
       <dd><a href="#" title="our trails">Sacramento River Parkway</a></dd>
     <dt>Santa Barbara</dt>
       <dd><a href="#" title="our trails">Atascadero Creek Trail</a></dd>
       <dd><a href="#" title="our trails">Santa Maria Valley Loop</a></dd>
     <dt>Santa Clara</dt>
       <dd><a href="#" title="our trails">Bol Park</a></dd>
       <dd><a href="#" title="our trails">Carpet Bomber</a></dd>
       <dd><a href="#" title="our trails">Evergreen Creek</a></dd>
     <dt>Sonoma</dt>
       <dd><a href="#" title="our trails">Foss Creek Wet Loop</a></dd>
       <dd><a href="#" title="our trails">Fountaincreek Trail</a></dd>
       <dd><a href="#" title="our trails">Petaluma Southern Loop</a></dd>
     <dt>Ventura</dt>
       <dd><a href="#" title="our trails">Channel Islands Trail</a></dd>
       <dd><a href="#" title="our trails">Ojai Valley</a></dd>
    </dl>  
    <h3>Ojai Trails</h3>
  </header>
  <article>
    <h2>Northridge Loop</h2>
      <table id="quickFacts">
      <caption>
      Trail INFO
      </caption>
      <tr>
        <th>trail type:</th>
        <td>single track</td>
      </tr>
      <tr>
        <th>elevation:</th>
        <td>2000 ft</td>
      </tr>
      <tr>
        <th>length:</th>
        <td>14.5 miles</td>
      </tr>
      <tr>
        <th>skill level:</th>
        <td>beginner to intermediate</td>
      </tr>
      </table>
      <p>If you are looking for great scenery and a great workout
        without all the technical difficulty of other trails,
        Northridge Loop is for you. The ridge runs east to west, with Ojai Valley on one 
        side and Rose Valley on the other. The trail features amazing views of both valleys plus the 
        Los Padres National Forest. </p>
      <p>There are a total of 6 trail heads spread out over the 14.5 mile loop, so there are
        plenty of places to get on or off the trail. Hiking is permitting along all trails, so ride 
        with caution and don't override your stopping power. </p>
      <p>While the overall trail is fine for beginners, two spurs, Gridley and Pratt, are much
        narrower and technical, so be sure to check the signage before choosing a trail. </p>
        <figure>
        <figcaption class="fig">Trail Map Elevation</figcaption>
          <img src="assets/trail_map.jpg" alt="Northridge Trail Map" title="Northiridge Trail Map">
          <img src="assets/trail_elevation.jpg" alt="Northridge Trail Elevation" title="Northiridge Trail Elevation">
        <!-- <figcaption> could also be placed here to show at bottom of photo --!>
        </figure>
      <h3>Skill level</h3>
      <h3>Surface</h3>
      <p>Most of the lower trails are firebreak roads or other, wide access roads. As you climb, trails
        become single track and a bit more technical. There are patches of bare rock and loose rock is 
        a common on most downhill sections. If you choose to ascend bia the Killabase Road trail
        head, the first quarter mile is paved path.
      </p>
      <h3>Notable features</h3>
      <p>While there aren't any huge jumps or insanely technical sections of the trail, 
        there are some areas that are worth taking the time to explore. Our favorite is known as 
        "Jacob's Ladder," a 25 foot section of rail road ties, iron rebar, and carpet (yes carpet) 
        strips just off the Casidas Park firebreak. Climbing this makeshift purchase point is a
        joy, and presents a decent challenge to all but the serious competitive climber. Recently
        I've heard that some of the more adventurous bikers have been descending it as a series of 
        jumps. If you want to give this a try you need to be extra careful, the washout resumes at 
        the bottom of it and is perched on the edge of a 700 foot drop. So consider yourself warned!
      </p>
     <blockqoute>
      <q>Northridge Loop is easily the best loop in Ojai! You’ll kick yourself if you miss it!</q>
         <footer>
         Nick Brazzi &#8212;<cite>The Complete Guide to Trails</cite>
         </footer>
      </blockqoute>
      <h3>Final thoughts</h3>
    <footer>
     <p>About the author:</p>
      <address>Jeff layton lives in Ventura, California with
        his wife, small dog, and various house plants and 
        writes about biking, Explore California, and the 
        outdoors. Contact him at <a href"mailto:jeff@explorecalifornia.org>jeff@explorecalifornia.org</a>
      </address>
    </footer>
  <section>
    <h2>Comments</h2>
  </section>
    <article>
      <h2><span>Max Smith wrote this on <time>April 25th, 2011 at 12:52</time></span></h2>
    </article>
  </article>
</section>
<article id=“riderReviews>
  <h2>Rider Reviews</h2>
  <article>
  <header>
  <hgroup>
    <h2>Los Robles Trail</h2>
    <h3>by Justin Vyn</h3>
  </hgroup>
    <p>submitted on 02/23/10</p>
  </header>
  </article>
  <article>
  <header>
  <hgroup>
    <h2>Copper Canyon Loop</h2>
    <h3>by Shea Hansen </h3>
  </hgroup>
    <p>submitted on 03/11/11</p>
  </header>
  </article>
</article>
<aside id=“adCopy”>
</aside>
<footer id=“pageFooter”>
<!-- <div class="rightCol"> --!>
<div class="pull-right">
<a href=#mainHeader"><p>return to top</p></a> <!-- notice this links within the page --!>
<p><a href="tel://866-555-4310" title="give us a call">T: 866.555.4310</a></p>
<p><a href="mailto:info@explorecalifornia.org">info@explorecalifornia.org</a></p> <!-- not reccommended due to spam risk --!>
</div>
<!-- <div class="leftCol"> --!>
<div class="pull-left">
<p><small>all content &copy;copyright 2011 Explpore California.org | please read our <a href="terms.htm" title="our terms of use">terms of use</a></p>
<p><b>Explore California</b></small></p>
<p>5605 Nota Street<br>
  Ventura, CA 93003
</p>
<p>866.555.4310<br>
  866.555.4315 <i>(24 hour support)</i>
</p>
</div>
</footer>
</body>
</html>

app/views/studies/practice2.html.erb
<!--
<%= @response %>
--!>

app/views/studies/practice3.html.erb
Practice 3 - javascript

<script>name</script>

<!-- %= sample("print this 3 times") %> --!>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "studies" %>
<p style="font-size: 13pt;">
  <strong>Name:</strong>
  <%= @study.name %>
</p><br>

<p style="font-size: 11pt;">
  <strong>Next up:</strong>
  <%= @study.next_up %>
</p><br>

<p>
  <strong>Done for today:</strong>
  <%= @study.done_for_today %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @study.deadline %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @study.priority %>
</p>

<p>
  <strong>Category:</strong>
  <%= @study.category %>
</p>

<p>
  <strong>Links:</strong>
  <%= @study.links %>
</p>
<!--
<p>
  <strong>Material:</strong><br>
  % @study.material.each do |key, value| %>
  %= "#{key}: #{value}" %><br>
  % end %>
</p>
--!>

<p>
  <strong>Completed:</strong>
  <%= @study.completed %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @study.notes %>
</p><br>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>